name: Downloader

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Clone source code
      run: |
       curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
       chmod +x repo
       ./repo init -u git://source.codeaurora.org/quic/cc-qrdk/releases/manifest/qstak -b release -m caf_AU_LINUX_QSDK_NHSS.QSDK.12.1.R2_TARGET_ALL.12.1.02.841.013.xml
       ls
       ./repo sync
       ls

    - name: Check space usage
      run: df -hT

    - name: Commit files
      env:
       github_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "782558181@qq.com"
        git config --global user.name "ZarkZero"
        rm -rf .repo/mainfests
        git rm --cached .repo/manifests
        git init
        git checkout main
        git add .
        git commit -m -q "Add changes"
        git remote add origin https://ZarkZero:${{ env.github_token }}@github.com/ZarkZero/qsdk-ax6
        git pull --rebase origin main
        git push -u -q origin main

    - name: Check space usage again
      run: df -hT
 
