name: Download-anything

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"

    - name: Clone source code
      run: |
       curl https://storage.googleapis.com/git-repo-downloads/repo -o repo
       chmod +x repo
       ./repo init -u git://source.codeaurora.org/quic/cc-qrdk/releases/manifest/qstak -b release -m caf_AU_LINUX_QSDK_NHSS.QSDK.11.5.0.5.R7_TARGET_ALL.12.0.000.934.009.xml
       ls
       ./repo sync
       ls

    - name: Achieve
      run: |
       cd ..
       mkdir packup
       7z a -t7z packup/qsdk-11.7z /home/runner/work/qsdk-ax6/qsdk-ax6/* -ms=4g -mx=9 -mf -mhc -mhcf -m0=LZMA2:a=2:d=26:fb=64 -mmt

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: qsdk-ax6
        path: /home/runner/work/qsdk-ax6/packup
